name = "premier-properties"
compatibility_date = "2024-01-01"

# Cloudflare Pages Configuration
pages_build_output_dir = "."

# Build configuration
[build]
command = "npm run build"
cwd = "."

[env.production]
name = "premier-properties"
routes = ["premierproperties.pages.dev/*", "www.premierproperties.com/*", "premierproperties.com/*"]

[env.preview]
name = "premier-properties-preview"
